
package elgranhotel.vista;

//import elgranhotel.vista.VistaHabitacion;
import elgranhotel.modelo.Conexion;
import elgranhotel.modelo.ReservaData;
import elgranhotel.modelo.RunnableClass;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Principal extends javax.swing.JFrame {
    
    private Conexion conexion;
    private ReservaData reservaData;
    
    public Principal() {
        initComponents();
        finReservaAutomatico();
          
        try {
            conexion = new Conexion("jdbc:mysql://localhost/hotel", "root", "");
            reservaData= new ReservaData(conexion);
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
            
                
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuHuesped = new javax.swing.JMenu();
        jMenuItemABMHuesped = new javax.swing.JMenuItem();
        jMenuReserva = new javax.swing.JMenu();
        jMenuItemABMReserva = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuHabitacion = new javax.swing.JMenu();
        jMenuItemABMHabitacion = new javax.swing.JMenuItem();
        jMenuTipoHabitacion = new javax.swing.JMenu();
        jMenuItemABMTipoHabitacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("El Gran Hotel 1.0-Grupo 7");
        setPreferredSize(new java.awt.Dimension(800, 600));

        escritorio.setPreferredSize(new java.awt.Dimension(800, 577));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("");

        jMenuArchivo.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuHuesped.setText("Huesped");
        jMenuHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHuespedActionPerformed(evt);
            }
        });

        jMenuItemABMHuesped.setText("ABM Huesped");
        jMenuItemABMHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABMHuespedActionPerformed(evt);
            }
        });
        jMenuHuesped.add(jMenuItemABMHuesped);

        jMenuBar1.add(jMenuHuesped);

        jMenuReserva.setText("Reserva");

        jMenuItemABMReserva.setText("Reservar");
        jMenuItemABMReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABMReservaActionPerformed(evt);
            }
        });
        jMenuReserva.add(jMenuItemABMReserva);

        jMenuItem1.setText("Buscar Reserva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuReserva.add(jMenuItem1);

        jMenuBar1.add(jMenuReserva);

        jMenuHabitacion.setText("Habitación");

        jMenuItemABMHabitacion.setText("ABM Habitación");
        jMenuItemABMHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABMHabitacionActionPerformed(evt);
            }
        });
        jMenuHabitacion.add(jMenuItemABMHabitacion);

        jMenuBar1.add(jMenuHabitacion);

        jMenuTipoHabitacion.setText("Tipo Habitacion");
        jMenuTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTipoHabitacionActionPerformed(evt);
            }
        });

        jMenuItemABMTipoHabitacion.setText("ABM tipo Habitacion");
        jMenuItemABMTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABMTipoHabitacionActionPerformed(evt);
            }
        });
        jMenuTipoHabitacion.add(jMenuItemABMTipoHabitacion);

        jMenuBar1.add(jMenuTipoHabitacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHuespedActionPerformed
        
    }//GEN-LAST:event_jMenuHuespedActionPerformed

    private void jMenuItemABMHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABMHuespedActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuesped vistaHuesped =new VistaHuesped();
        vistaHuesped.setVisible(true);
        escritorio.add(vistaHuesped);
        escritorio.moveToFront(vistaHuesped);
    }//GEN-LAST:event_jMenuItemABMHuespedActionPerformed

    private void jMenuItemABMHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABMHabitacionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHabitacion vistaHabitacion =new VistaHabitacion();
        vistaHabitacion.setVisible(true);
        escritorio.add(vistaHabitacion);
        escritorio.moveToFront(vistaHabitacion);
    }//GEN-LAST:event_jMenuItemABMHabitacionActionPerformed

    private void jMenuItemABMReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABMReservaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaReserva vistaReserva =new VistaReserva();
        vistaReserva.setVisible(true);
        escritorio.add(vistaReserva);
        escritorio.moveToFront(vistaReserva);
    }//GEN-LAST:event_jMenuItemABMReservaActionPerformed

    private void jMenuTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTipoHabitacionActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        VistaTipoHabitacion vistaTipoHabitacion =new VistaTipoHabitacion();
        vistaTipoHabitacion.setVisible(true);
        escritorio.add(vistaTipoHabitacion);
        escritorio.moveToFront(vistaTipoHabitacion);
    }//GEN-LAST:event_jMenuTipoHabitacionActionPerformed

    private void jMenuItemABMTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABMTipoHabitacionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaTipoHabitacion vistaTipoHabitacion =new VistaTipoHabitacion();
        vistaTipoHabitacion.setVisible(true);
        escritorio.add(vistaTipoHabitacion);
        escritorio.moveToFront(vistaTipoHabitacion);
    }//GEN-LAST:event_jMenuItemABMTipoHabitacionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    escritorio.removeAll();
        escritorio.repaint();
        VistaBuscarReserva vistaBuscarReserva =new VistaBuscarReserva();
        vistaBuscarReserva.setVisible(true);
        escritorio.add(vistaBuscarReserva);
        escritorio.moveToFront(vistaBuscarReserva);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

          
    public void finReservaAutomatico(){
       
        
       /* LocalDateTime localNow = LocalDateTime.now();
        ZoneId currentZone = ZoneId.of("Argentina");
        ZonedDateTime zonedNow = ZonedDateTime.of(localNow, currentZone);
        ZonedDateTime zonedNext5 ;
        zonedNext5 = zonedNow.withHour(0).withMinute(0).withSecond(0);
        if(zonedNow.compareTo(zonedNext5) > 0)
            zonedNext5 = zonedNext5.plusDays(1);

        Duration duration = Duration.between(zonedNow, zonedNext5);
        long initalDelay = duration.getSeconds();*/

        ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
        scheduler.scheduleAtFixedRate(new RunnableClass(conexion) , 0, 24*60*60, TimeUnit.SECONDS);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenuArchivo;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHabitacion;
    private javax.swing.JMenu jMenuHuesped;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemABMHabitacion;
    private javax.swing.JMenuItem jMenuItemABMHuesped;
    private javax.swing.JMenuItem jMenuItemABMReserva;
    private javax.swing.JMenuItem jMenuItemABMTipoHabitacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuReserva;
    private javax.swing.JMenu jMenuTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
