
package elgranhotel.vista;

import elgranhotel.vista.VistaHabitacion;
import elgranhotel.vista.VistaHuesped;
import elgranhotel.vista.VistaReserva;
//import elgranhotel.vista.VistaTipoHabitacion;

public class Principal extends javax.swing.JFrame {

    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuHuesped = new javax.swing.JMenu();
        jMenuABMHuesped = new javax.swing.JMenuItem();
        jmiBuscarReservaPorFecha = new javax.swing.JMenu();
        jmiReserva = new javax.swing.JMenuItem();
        jmiBuscarReservaPorHuesped = new javax.swing.JMenuItem();
        jMenuHabitacion = new javax.swing.JMenu();
        jMenuABMHabitacion = new javax.swing.JMenuItem();
        jMenuTipoHabitacion = new javax.swing.JMenu();
        jMenuItemABMTipoHabitacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(800, 577));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuHuesped.setText("Huesped");
        jMenuHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHuespedActionPerformed(evt);
            }
        });

        jMenuABMHuesped.setText("ABM Huesped");
        jMenuABMHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuABMHuespedActionPerformed(evt);
            }
        });
        jMenuHuesped.add(jMenuABMHuesped);

        jMenuBar1.add(jMenuHuesped);

        jmiBuscarReservaPorFecha.setText("Reserva");

        jmiReserva.setText("Reservar");
        jmiReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReservaActionPerformed(evt);
            }
        });
        jmiBuscarReservaPorFecha.add(jmiReserva);

        jmiBuscarReservaPorHuesped.setText("Buscar Reserva");
        jmiBuscarReservaPorHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarReservaPorHuespedActionPerformed(evt);
            }
        });
        jmiBuscarReservaPorFecha.add(jmiBuscarReservaPorHuesped);

        jMenuBar1.add(jmiBuscarReservaPorFecha);

        jMenuHabitacion.setText("Habitación");

        jMenuABMHabitacion.setText("ABM Habitación");
        jMenuABMHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuABMHabitacionActionPerformed(evt);
            }
        });
        jMenuHabitacion.add(jMenuABMHabitacion);

        jMenuBar1.add(jMenuHabitacion);

        jMenuTipoHabitacion.setText("Tipo Habitacion");
        jMenuTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTipoHabitacionActionPerformed(evt);
            }
        });

        jMenuItemABMTipoHabitacion.setText("ABM tipo Habitacion");
        jMenuItemABMTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemABMTipoHabitacionActionPerformed(evt);
            }
        });
        jMenuTipoHabitacion.add(jMenuItemABMTipoHabitacion);

        jMenuBar1.add(jMenuTipoHabitacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHuespedActionPerformed
        
    }//GEN-LAST:event_jMenuHuespedActionPerformed

    private void jMenuABMHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuABMHuespedActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuesped vistaHuesped =new VistaHuesped();
        vistaHuesped.setVisible(true);
        escritorio.add(vistaHuesped);
        escritorio.moveToFront(vistaHuesped);
    }//GEN-LAST:event_jMenuABMHuespedActionPerformed

    private void jMenuABMHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuABMHabitacionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHabitacion vistaHabitacion =new VistaHabitacion();
        vistaHabitacion.setVisible(true);
        escritorio.add(vistaHabitacion);
        escritorio.moveToFront(vistaHabitacion);
    }//GEN-LAST:event_jMenuABMHabitacionActionPerformed

    private void jmiReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReservaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaReserva vistaReserva =new VistaReserva();
        vistaReserva.setVisible(true);
        escritorio.add(vistaReserva);
        escritorio.moveToFront(vistaReserva);
    }//GEN-LAST:event_jmiReservaActionPerformed

    private void jMenuTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTipoHabitacionActionPerformed
        
    }//GEN-LAST:event_jMenuTipoHabitacionActionPerformed

    private void jMenuItemABMTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemABMTipoHabitacionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
  //      VistaTipoHabitacion vistaTipoHabitacion =new VistaTipoHabitacion();
    //    vistaTipoHabitacion.setVisible(true);
      //  escritorio.add(vistaTipoHabitacion);
       // escritorio.moveToFront(vistaTipoHabitacion);
    }//GEN-LAST:event_jMenuItemABMTipoHabitacionActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jmiBuscarReservaPorHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarReservaPorHuespedActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaBuscarReserva vBuscarReserva =new VistaBuscarReserva();
        vBuscarReserva.setVisible(true);
        escritorio.add(vBuscarReserva);
        escritorio.moveToFront(vBuscarReserva);
    }//GEN-LAST:event_jmiBuscarReservaPorHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuABMHabitacion;
    private javax.swing.JMenuItem jMenuABMHuesped;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHabitacion;
    private javax.swing.JMenu jMenuHuesped;
    private javax.swing.JMenuItem jMenuItemABMTipoHabitacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuTipoHabitacion;
    private javax.swing.JMenu jmiBuscarReservaPorFecha;
    private javax.swing.JMenuItem jmiBuscarReservaPorHuesped;
    private javax.swing.JMenuItem jmiReserva;
    // End of variables declaration//GEN-END:variables
}
